#!/bin/bash

db=/opt/reductor_web/app/db/reductor.db

[ ! -f $db ] && touch $db

if [ "$(sqlite3 $db .tables | wc -w)" -lt 6 ]; then
	sqlite3 $db "CREATE TABLE rxtx(dev text, x text, count int, bytes unsigned big int, date unsigned big int);"
	sqlite3 $db "CREATE TABLE packets_checked(checked unsigned big int, matched unsigned int, date unisgned big int);"
	sqlite3 $db 'CREATE TABLE list_actuality(list text, delta big int, date unsigned big int);'
	sqlite3 $db 'CREATE TABLE usedcpu(used unsigned int, date unsigned big int);'
	sqlite3 $db 'CREATE TABLE usedmem(used unsigned int, date unsigned big int);'
	find /opt/reductor_web/scripts/ -type f -name "*_update" -exec {} \; &
fi
