#!/bin/bash

. /usr/local/Reductor/etc/const

file=$SSLDIR/php/register.zip
current_date=$(date +%s)

if ! [ -f $file ]; then
	echo "${file##*/} -1 $current_date"
	file=$SSLDIR/php/dump.xml
	if ! [ -f $file ]; then
		echo "${file##*/} -1 $current_date"
		exit 0
	fi
fi

last_modify_date=$(stat -c "%Y" $file)
delta="$((current_date - last_modify_date))"
echo "${file##*/} $delta $current_date"
