#!/bin/bash

date=$(date +%s)
prog=${0##*/}
db=/opt/reductor_web/app/db/reductor.db
tmp=/tmp/reductor/$prog

/opt/reductor_web/scripts/${prog%%_update} > $tmp

while read file delta current t; do
	sqlite3 $db "insert into list_actuality values('$file', $delta, $current)"
done < $tmp

sqlite3 $db "delete from list_actuality where date < $(($(date +%s)-(7*24*60*60*30)))"
