#!/bin/bash

date=$(date +%s)
prog=${0##*/}
db=/opt/reductor_web/app/db/reductor.db
tmp=/tmp/reductor/$prog

/opt/reductor_web/scripts/${prog%%_update} > $tmp

while read checked matched t; do
	sqlite3 $db "insert into ${prog%%_update} values ($checked, $matched, $date)"
done < $tmp

sqlite3 $db "delete from ${prog%%_update} where date < $(($(date +%s)-(7*24*60*60*30)))"
