#!/bin/bash

. /usr/local/Reductor/etc/const

packets_matched() {
	grep "^Matched" $PROCLIST | egrep -o "[0-9]+"
}

packets_checked() {
	grep "^Total" $PROCLIST | egrep -o "[0-9]+"
}

main() {
	check_prev=$(packets_checked)
	match_prev=$(packets_matched)
	sleep 60
	check_next=$(packets_checked)
	match_next=$(packets_matched)
	echo $((check_next-check_prev)) $((match_next-match_prev))
}

case ${1:-main} in
	main | packets_matched | packets_checked )
		${1:-main}
		;;
	* )
		echo "$1 not supported" >&2
		;;
esac
