#!/bin/bash

mkdir -p /tmp/reductor
devlist="egrep -o eth[0-9\.]+ /proc/net/dev"

x() {
	grep "${1:-eth1}:" /proc/net/dev | tr : ' '
}

rx() {
	x $1 | awk '{print $2" "$3}'
}

tx() {
	x $1 | awk '{print $10" "$11}'
}

for s in 1 2; do
	for i in $($devlist); do
		wi=${i//./_}
		for f in rx tx; do
			echo $f$s$wi='"'$($f $i)'"'
		done
	done
	[ "$s" = '1' ] && sleep 1
done > /tmp/reductor/xps

source /tmp/reductor/xps

for i in $($devlist); do
	for f in rx tx; do
		wi=${i//./_}
		var_p=p$f$wi var_b=b$f$wi var1=${f}1$wi var2=${f}2$wi
		vv1="${!var1}"
		vv2="${!var2}"
		eval $var_p=\$\(\(${vv2##* }-${vv1##* }\)\)
		eval $var_b=\$\(\(${vv2%% *}-${vv1%% *}\)\)
		echo $i $f ${!var_p} ${!var_b}
	done
done
