#!/bin/bash

date=$(date +%s)
prog=${0##*/}
db=/opt/reductor_web/app/db/reductor.db
tmp=/tmp/reductor/$prog

/opt/reductor_web/scripts/${prog%%_update} > $tmp

while read dev x count bytes tmp; do
	sqlite3 $db "insert into rxtx values('$dev', '$x', '$count', $bytes, $date)"
done < $tmp

sqlite3 $db "delete from rxtx where date < $(($(date +%s)-(7*24*60*60*30)))"
